#
# This is the server logic of a Shiny web application. You can run the
# application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

# 3rd party packages
library(shiny)

# Own packages
library(model)

# File that contains all the sampled data from our text feeds.
# This data file is generated by the `scripts/ngramGen.R` script.
load("ngrams.dat")

# Define server logic required to draw a histogram
shinyServer(function(input, output) {

  output$suggestion1 <- renderUI({
    actionButton("suggestion1", label = "hey")
  })
  output$suggestion2 <- renderUI({
    actionButton("suggestion2", label = "how")
  })
  output$suggestion3 <- renderUI({
    actionButton("suggestion3", label = "ru")
  })

})
