#
# This is the server logic of a Shiny web application. You can run the
# application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

# 3rd party packages
library(shiny)

# Own packages
library(model)

# File that contains all the sampled data from our text feeds.
# This data file is generated by the `scripts/ngramGen.R` script.
load("ngrams.dat")

updateText <- function(input, session, newWord) {
  textInput <- input$text
  newText <- paste(textInput, newWord, sep = "")
  newText <- paste(newText, " ", sep = "")  # Append whitespace at the end
  updateTextAreaInput(session, "text", value = newText)
}

# Define server logic required to draw a histogram
shinyServer(function(input, output, session) {

  suggestions <- reactive({
    suggestNextWords(input$text, ngrams)
  })

  observeEvent(input$suggestion1, {
    newWord <- suggestions()[1]
    updateText(input, session, newWord)
  })

  observeEvent(input$suggestion2, {
    newWord <- suggestions()[2]
    updateText(input, session, newWord)
  })

  observeEvent(input$suggestion3, {
    newWord <- suggestions()[3]
    updateText(input, session, newWord)
  })

  output$suggestion1 <- renderUI({
    actionButton("suggestion1", label = suggestions()[1])
  })
  output$suggestion2 <- renderUI({
    actionButton("suggestion2", label = suggestions()[2])
  })
  output$suggestion3 <- renderUI({
    actionButton("suggestion3", label = suggestions()[3])
  })

})
